config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end

  get '/add_course/:id/:course_id', to: 'users#add_course', as: 'add_course'
  get '/remove_course/:id/:course_id', to: 'users#remove_course', as: 'remove_course'

  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  get "screencast/convert_video/:id" ,to: "screencasts#convert_video", as: "screencast_convert_video"
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]

  resources :regions do
    resources :schools, only: [:index,:new, :create, :destroy]
  end
  resources :schools, only: [:show, :edit, :update]
  
  resources :testings do
    resources :probs, only: [:index,:new, :create, :destroy]
  end
  resources :probs, only: [:show, :edit, :update] do 
    resources :opts, only: [:index,:new, :create, :destroy]
  end
  resources :opts, only: [:show, :edit, :update] 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

app/models/exam.rb
class Exam < ApplicationRecord
  attr_accessor :opts
  belongs_to :section
  has_many :answers, dependent: :destroy
  has_many :pics, dependent: :destroy
end

app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

app/models/opt.rb
class Opt < ApplicationRecord
  belongs_to :prob
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/prob.rb
class Prob < ApplicationRecord
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
  belongs_to :testing
  has_many :opts, dependent: :destroy

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  attr_accessor :opts
  belongs_to :screencast
  has_many :options, dependent: :destroy
  has_many :imgs, dependent: :destroy
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :schools, dependent: :destroy

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :region
end

app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

app/models/testing.rb
class Testing < ApplicationRecord
  has_many :probs
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses,:dependent => :destroy
  has_many :payments
  has_many :courseProgresses, :dependent => :destroy
  has_many :sectionProgresses, :dependent => :destroy
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user_section.rb
class UserSection < ApplicationRecord
  belongs_to :user
end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
  before_action :set_testing, only: [:show, :edit, :update, :destroy]

  def index
    @testings = Testing.all
  end

  def show
  end

  def new
    @testing = Testing.new
    @testing.lang=0
  end

  def edit
  end

  def create
    @testing = Testing.new(testing_params)
    respond_to do |format|
      if @testing.save
        format.html { redirect_to @testing, notice: 'Testing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @testing.update(testing_params)
        format.html { redirect_to @testing, notice: 'Testing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @testing.destroy
    respond_to do |format|
      format.html { redirect_to testings_url, notice: 'Testing was successfully destroyed.' }
    end
  end

  private
    def set_testing
      @testing = Testing.find(params[:id])
    end

    def testing_params
      params.require(:testing).permit(:lang,:name, :description,:duration,:free)
    end
end

app/views/testings/_form.html.erb
<%= form_with(model: testing, local: true) do |form| %>
  <% if testing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testing.errors.count, "error") %> prohibited this testing from being saved:</h2>

      <ul>
        <% testing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name,'Название'  %>
    <%= form.text_field :name, id: :testing_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :lang,'Язык обучения(0-кыр.1-рус.)' %>
    <%= form.text_field :lang, id: :testing_lang, class:"form-control" %>
  </div>
  <div class="field form-group">
    <div class="checkbox-inline">
      <%= form.check_box :free%>
      <%= form.label :free, "Открытый доступ" %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :description,'Описание'  %>
    <%= form.text_area :description, id: :testing_description , class:"form-control" ,:cols => 40, :rows => 6 %>
  </div>
  <div class="field form-group">
    <%= form.label :duration,'Длительность в мин.' %>
    <%= form.text_field :duration, id: :testing_duration, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", class:"btn btn-outline-primary" %>
    <%= link_to 'Отмена', testings_path,class:"btn btn-outline-primary" %>
  </div>
<% end %>

app/views/testings/edit.html.erb
<h1>Изменение</h1>

<%= render 'form', testing: @testing %>

app/views/testings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список пробных тестов</h1>

<table class="table">
  <thead>
    <tr>
      <th>Название</th>
      <th>Язык обучения</th>
      <th>Доступ</th>
      <th>Длительность</th>
      <th>Описание</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testings.each do |testing| %>
      <tr>
        <td><%= testing.name %></td>
        <td><%= testing.lang==0 ? "Кыргызча" : "Русский" %></td>
        <td><%= testing.free ? "открытый" : "закрытый"%></td>
        <td><%= testing.duration %> мин.</td>
        <td><%= testing.description %></td>
        <td><%= link_to 'Открыть', testing %></td>
        <td><%= link_to 'Редактировать', edit_testing_path(testing) %></td>
        <td><%= link_to 'Удалить', testing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый пробный тест', new_testing_path %>

app/views/testings/new.html.erb
<h1>Новый пробный тест</h1>
<%= render 'form', testing: @testing %>

app/views/testings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <%= @testing.name %>
  </div>
  <div class="card-body">
    <p class="card-text">Язык обучения: <%= @testing.lang==0 ? "Кыргызча" : "Русский" %></p>
    <p class="card-text">Доступ: <%= @testing.free ? "открытый" : "закрытый"%></p>
    <p class="card-text">Длительность : <%= @testing.duration %> мин.</p>
    <p class="card-text">Описание: <%= @testing.description %></p>
    <div class="clearfix">
      <%= link_to 'Редактировать', edit_testing_path(@testing), class:"btn btn-outline-primary"%> 
      <%= link_to 'Вернуться в список пробных тестов', testings_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header">
    Вопросы и инструкции 
  </div>

  <div class="card-body">
    <table class="table">

      <thead>
        <tr>
          <th>#</th>
          <th>Вопрос/текст</th>
          <th>Рис.</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @testing.probs.order(:no).each do |prob| %>
          <tr>
            <td><%= prob.no %><small><%= prob.isinstruction ? "Инсi" : "Воп" %></small></td>
            <td style="max-witdh:300px"><%= prob.question %><br><b>Детали</b><br><%= prob.details %></td>
            <td><%= image_tag prob.img.url(:thumb) %></td>
            <td>
              <% if !prob.isinstruction %>
                <%= link_to 'Варианты ответов', prob %>
                <% prob.opts.each do |opt| %>
                  <br>
                  <%= (opt.correct ? "+ " : "- ") + opt.value %>
                <% end %>
              <% end %>
              </td>
            <td><%= link_to 'Изменить', edit_prob_path(prob) %><br><%= link_to 'Удалить', [@testing,prob], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %> </tbody>
    </table>
    <%= link_to 'Новый вопрос', new_testing_prob_path(@testing) ,class:"btn btn-outline-secondary" %>
  </div>
</div>
<br>