config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end

  get '/add_course/:id/:course_id', to: 'users#add_course', as: 'add_course'
  get '/remove_course/:id/:course_id', to: 'users#remove_course', as: 'remove_course'

  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  get "screencast/convert_video/:id" ,to: "screencasts#convert_video", as: "screencast_convert_video"
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]

  resources :regions do
    resources :schools, only: [:index,:new, :create, :destroy]
  end
  resources :schools, only: [:show, :edit, :update]
  
  resources :testings do
    resources :probs, only: [:index,:new, :create, :destroy]
  end
  resources :probs, only: [:show, :edit, :update] do 
    resources :opts, only: [:index,:new, :create, :destroy]
  end
  resources :opts, only: [:show, :edit, :update] 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

app/models/exam.rb
class Exam < ApplicationRecord
  attr_accessor :opts
  belongs_to :section
  has_many :answers, dependent: :destroy
  has_many :pics, dependent: :destroy
end

app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

app/models/opt.rb
class Opt < ApplicationRecord
  belongs_to :prob
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/prob.rb
class Prob < ApplicationRecord
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
  belongs_to :testing
  has_many :opts, dependent: :destroy

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  attr_accessor :opts
  belongs_to :screencast
  has_many :options, dependent: :destroy
  has_many :imgs, dependent: :destroy
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :schools, dependent: :destroy

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :region
end

app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

app/models/testing.rb
class Testing < ApplicationRecord
  has_many :probs
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses,:dependent => :destroy
  has_many :payments
  has_many :courseProgresses, :dependent => :destroy
  has_many :sectionProgresses, :dependent => :destroy
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user_section.rb
class UserSection < ApplicationRecord
  belongs_to :user
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subject.lang=0
    @subject.no = Subject.maximum(:no) ? Subject.maximum(:no)+1 : 1
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:no,:lang,:name, :description, :logo)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :no, 'Порядковый номер'%>
    <%= form.text_field :no, id: :subject_no, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :name,'Название'  %>
    <%= form.text_field :name, id: :subject_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :lang,'Язык обучения(0-кыр.1-рус.)' %>
    <%= form.text_field :lang, id: :subject_lang, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description,'Описание'  %>
    <%= form.text_field :description, id: :subject_description , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :logo, 'Лого' %>
    <%= form.file_field :logo, id: :subject_logo , class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", class:"btn btn-outline-primary" %>
<%= link_to 'Отмена', subjects_path,class:"btn btn-outline-primary" %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Редактирование направления</h1>

<%= render 'form', subject: @subject %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список направлений</h1>

<table class="table">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Логотип</th>
      <th>Название</th>
      <th>Язык обучения</th>
      <th>Описание</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.no %></td>
        <td><%= image_tag subject.logo.url(:thumb) %></td>
        <td><%= subject.name %></td>
        <td><%= subject.lang==0?"Кыргызча":"Русский" %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Открыть', subject %></td>
        <td><%= link_to 'Редактировать', edit_subject_path(subject) %></td>
        <td><%= link_to 'Удалить', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новое направление', new_subject_path %>

app/views/subjects/new.html.erb
<h1>Новое направление</h1>
<%= render 'form', subject: @subject %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <%= @subject.no %>.<%= @subject.name %>
  </div>
  <div class="card-body">
    <%= image_tag @subject.logo.url(:medium), class:"rounded float-left mr-3" %>
    <p class="card-text">Язык обучения: <%= @subject.lang==0?"Кыргызча":"Русский" %></p>
    <p class="card-text">Описание: <%= @subject.description %></p>
    <div class="clearfix">
      <%= link_to 'Редактировать', edit_subject_path(@subject), class:"btn btn-outline-primary"%> 
      <%= link_to 'Отмена', subjects_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header">
    Курсы по направлению 
  </div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Номер</th>
          <th>Логотип</th>
          <th>Название</th>
          <th>Описание</th>
          <th>Уровень</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @subject.courses.order(:no).each do |course| %>
          <tr>
            <td><%= course.no %></td>
            <td><%= image_tag course.logo.url(:thumb) %></td>
            <td><%= course.name %></td>
            <td><%= course.description %></td>
            <td><%= course.level %></td>
            <td><%= link_to 'Открыть', course %></td>
            <td><%= link_to 'Редактировать', edit_course_path(course) %></td>
            <td><%= link_to 'Удалить', [@subject,course], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= link_to 'Добавить новый курс', new_subject_course_path(@subject),class:"btn btn-outline-secondary" %>
  </div>
</div>
<br>