config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end

  get '/add_course/:id/:course_id', to: 'users#add_course', as: 'add_course'
  get '/remove_course/:id/:course_id', to: 'users#remove_course', as: 'remove_course'

  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  get "screencast/convert_video/:id" ,to: "screencasts#convert_video", as: "screencast_convert_video"
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]

  resources :regions do
    resources :schools, only: [:index,:new, :create, :destroy]
  end
  resources :schools, only: [:show, :edit, :update]
  
  resources :testings do
    resources :probs, only: [:index,:new, :create, :destroy]
  end
  resources :probs, only: [:show, :edit, :update] do 
    resources :opts, only: [:index,:new, :create, :destroy]
  end
  resources :opts, only: [:show, :edit, :update] 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

app/models/exam.rb
class Exam < ApplicationRecord
  attr_accessor :opts
  belongs_to :section
  has_many :answers, dependent: :destroy
  has_many :pics, dependent: :destroy
end

app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

app/models/opt.rb
class Opt < ApplicationRecord
  belongs_to :prob
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/prob.rb
class Prob < ApplicationRecord
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
  belongs_to :testing
  has_many :opts, dependent: :destroy

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  attr_accessor :opts
  belongs_to :screencast
  has_many :options, dependent: :destroy
  has_many :imgs, dependent: :destroy
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :schools, dependent: :destroy

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :region
end

app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

app/models/testing.rb
class Testing < ApplicationRecord
  has_many :probs
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses,:dependent => :destroy
  has_many :payments
  has_many :courseProgresses, :dependent => :destroy
  has_many :sectionProgresses, :dependent => :destroy
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_subject, only: [:index,:new, :create, :destroy]

  def index
    @courses = @subject.courses
  end

  def show
    @lectors = Lector.all
  end

  def new
    @course = @subject.courses.new
    @course.no = @subject.courses.maximum(:no) ? @subject.courses.maximum(:no)+1 : 1
  end

  def edit
  end

  def create
    @course = @subject.courses.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def add_lector 
    course = Course.find(params[:course_id])
    lector = Lector.find(params[:lector_id])
    course.lectors<<lector
    course.save
    respond_to do |format|
      format.html { redirect_to course }
    end
  end
  def remove_lector 
    course = Course.find(params[:course_id])
    lector = Lector.find(params[:lector_id])
    course.lectors.destroy(params[:lector_id])
    course.save
    respond_to do |format|
      format.html { redirect_to course }
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to @subject, notice: 'Course was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    def set_subject
      @subject = Subject.find(params[:subject_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:no, :name, :description, :logo, :subject_id, :level, :lector)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: [subject,course], local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :no,"Порядковый номер" %>
    <%= form.text_field :no, id: :course_no , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :name, "Название"%>
    <%= form.text_field :name, id: :course_name , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description,"Описание" %>
    <%= form.text_field :description, id: :course_description , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :logo,"Лого" %>
    <%= form.file_field :logo, id: :course_logo , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :level,"Сложность(1-5)" %>
    <%= form.number_field :level, id: :course_level , class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", class:"btn btn-outline-primary" %>
<%= link_to 'Отмена',subject||course,class:"btn btn-outline-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Редактирование курса</h1>

<%= render 'form', subject: @subject,course: @course %>

<%= link_to 'Сохранить', @course %> |
<%= link_to 'Отмена', @course.subject %>

app/views/courses/new.html.erb
<h1>Новый</h1>

<%= render 'form', {subject:@subject, course: @course} %>

<%= link_to 'Отмена', @subject %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <%= @course.no %>. <%= @course.name %>
  </div>
  <div class="card-body">
    <%image_tag @course.logo.url(:medium), class:"rounded float-left mr-3" %>
    <p class="card-text">Направление: <%=link_to @course.subject.name,@course.subject %></p>
    <p class="card-text">Описание: <%= @course.description %></p>
    <p><strong>Сложность: </strong><%= @course.level %></p>
    <div class="clearfix">
      <%= link_to 'Редактировать', edit_course_path(@course), class:"btn btn-outline-primary"%> 
      <%= link_to 'Вернуться в список курсов', @course.subject, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header"> Части курса <%=@course.name%></div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Номер</th>
          <th>Название</th>
          <th>Описание</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @course.sections.order(:no).each do |section| %>
          <tr>
            <td><%= section.no %></td>
            <td><%= section.name %></td>
            <td><%= section.description%></td>
            <td><%= link_to 'Открыть', section %></td>
            <td><%= link_to 'Редактировать', edit_section_path(section) %></td>
            <td><%= link_to 'Удалить', [@course,section], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Создать новую часть', new_course_section_path(@course),class:"btn btn-outline-secondary" %>
  </div>
</div>

<br>

<div class="card">
  <div class="card-header">Лекторы курса</div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Имя</th>
          <th>Уровень(1-5)</th>
          <th>Степень</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @course.lectors.each do |lector| %>
          <tr>
            <td><%= image_tag lector.photo.url(:thumb) %></td>
            <td><%= lector.fullname %></td>
            <td><%= lector.level %></td>
            <td><%= lector.degree %></td>
            <td><%= link_to 'Destroy', remove_lector_path(@course.id,lector.id), data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
    <a class="btn btn-outline-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Назначить учителя 
    </a>
    </p>
    <div class="collapse" id="collapseExample">
      <div class="card card-body">
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Имя</th>
              <th>Уровень(1-5)</th>
              <th>Степень</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @lectors.each do |lector| %>
              <tr>
                <td><%= image_tag lector.photo.url(:thumb) %></td>
                <td><%= lector.fullname %></td>
                <td><%= lector.level %></td>
                <td><%= lector.degree %></td>
                <td><%= link_to 'Select', add_lector_path(@course.id, lector.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>