config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "subjects#index"

  resources :lectors 

  resources :users do 
    resources :user_courses, only: [:index,:new,:create,:destroy]
  end

  get '/add_course/:id/:course_id', to: 'users#add_course', as: 'add_course'
  get '/remove_course/:id/:course_id', to: 'users#remove_course', as: 'remove_course'

  resources :user_courses, only: [:show, :edit, :update]


  resources :subjects do 
    resources :courses, only: [:index,:new,:create, :destroy] 
  end
  get '/add_lector/:course_id/:lector_id', to: 'courses#add_lector', as: 'add_lector'
  get '/remove_lector/:course_id/:lector_id', to: 'courses#remove_lector', as: 'remove_lector'
  resources :courses, only: [:show, :edit, :update] do
    resources :sections, only: [:index,:new, :create, :destroy]
  end
  resources :sections, only: [:show, :edit, :update] do
    resources :screencasts, only: [:index,:new, :create, :destroy]
    resources :exams, only: [:index,:new, :create, :destroy]
  end
  resources :screencasts, only: [:show, :edit, :update] do 
    resources :quizzes, only: [:index,:new, :create, :destroy]
  end
  get "screencast/convert_video/:id" ,to: "screencasts#convert_video", as: "screencast_convert_video"
  resources :quizzes, only: [:show, :edit, :update] do
    resources :options, only: [:index,:new, :create, :destroy]
    resources :imgs, only: [:index,:new, :create, :destroy]
  end
  resources :options, only: [:show, :edit, :update]
  resources :imgs, only: [:show, :edit, :update]

  resources :exams, only: [:show, :edit, :update] do
    resources :answers, only: [:index,:new, :create, :destroy]
    resources :pics, only: [:index,:new, :create, :destroy]
  end
  resources :answers, only: [:show, :edit, :update]
  resources :pics, only: [:show, :edit, :update]

  resources :regions do
    resources :schools, only: [:index,:new, :create, :destroy]
  end
  resources :schools, only: [:show, :edit, :update]
  
  resources :testings do
    resources :probs, only: [:index,:new, :create, :destroy]
  end
  resources :probs, only: [:show, :edit, :update] do 
    resources :opts, only: [:index,:new, :create, :destroy]
  end
  resources :opts, only: [:show, :edit, :update] 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exam
end

app/models/course.rb
class Course < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  belongs_to :subject
  has_many :sections
  has_and_belongs_to_many :lectors
end

app/models/exam.rb
class Exam < ApplicationRecord
  attr_accessor :opts
  belongs_to :section
  has_many :answers, dependent: :destroy
  has_many :pics, dependent: :destroy
end

app/models/img.rb
class Img < ApplicationRecord
  belongs_to :quiz
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/lector.rb
class Lector < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :courses
end

app/models/opt.rb
class Opt < ApplicationRecord
  belongs_to :prob
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :quiz
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :exam
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/prob.rb
class Prob < ApplicationRecord
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
  belongs_to :testing
  has_many :opts, dependent: :destroy

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  attr_accessor :opts
  belongs_to :screencast
  has_many :options, dependent: :destroy
  has_many :imgs, dependent: :destroy
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :schools, dependent: :destroy

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :region
end

app/models/screencast.rb
class Screencast < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/
  belongs_to :section
  has_many :quizzes
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :screencasts
  has_many :exams
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  has_many :courses
end

app/models/testing.rb
class Testing < ApplicationRecord
  has_many :probs
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  has_secure_password
  has_many :userCourses,:dependent => :destroy
  has_many :payments
  has_many :courseProgresses, :dependent => :destroy
  has_many :sectionProgresses, :dependent => :destroy
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user_section.rb
class UserSection < ApplicationRecord
  belongs_to :user
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :set_section, only: [:index,:new, :create, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = @section.exams
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = @section.exams.new
    @exam.score = 1
    @exam.no = @section.exams.maximum(:no)
    @exam.isformula = false
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = @section.exams.new(exam_params)

    respond_to do |format|
      if @exam.save
        opts = params[:exam][:opts].split("\n").reject(&:blank?)
        opts.each do |opt|
          @exam.answers.create(value:opt,correct:false)
        end
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to @section, notice: 'Exam was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end
    def set_section
      @section = Section.find(params[:section_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:no, :section_id, :question, :details, :score,:isformula)
    end
end

app/views/exams/_form.html.erb
<%= form_with(model: [section,exam], local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :no, "Сложность(1-10)" %>
    <%= form.text_field :no, id: :exam_no , class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :question, "Вопрос" %>
    <%= form.text_area :question, id: :exam_question , class:"form-control",cols:40,rows:3 %>
  </div>

  <div class="field form-group">
    <%= form.label :details, "Детали вопроса" %>
    <%= form.text_area :details, id: :exam_details, class:"form-control",:cols => 40, :rows => 10 %>
  </div>
  <div class="field form-group">
    <div class="checkbox-inline">
      <%= form.check_box :isformula%>
      <%= form.label :isformula, "Формула" %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :score, "Балл" %>
    <%= form.number_field :score, id: :exam_score, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :opts, "Варианты ответов(каждый вариант отдельной строкой)" %>
    <%= form.text_area :opts, id: :opts, class:"form-control",:cols => 40, :rows => 6 %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", class:"btn btn-outline-primary" %>
<%= link_to 'Отмена',section||exam,class:"btn btn-outline-primary" %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Редактирование вопроса</h1>

<%= render 'form', section: @section,exam: @exam %>

<%= link_to 'Открыть варианты ответов и рисунки в вопросу', @exam %> |
<%= link_to 'Отмена', @exam.section%>

app/views/exams/new.html.erb
<h1>Новый вопрос</h1>

<%= render 'form', {section: @section, exam: @exam} %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header"> 
    <%= @exam.no%>. <%= @exam.question%>
  </div>
  <div class="card-body">
    <p><strong>Детали к вопросу:</strong> <%= @exam.details %></p>
    <p><strong>Балл:</strong> <%= @exam.score %></p>
    <p><strong>Вопрос к секции:</strong> <%= link_to @exam.section.name, @exam.section%></p>
    <div class="clearfix">
      <%= link_to 'Edit EXAM Question', edit_exam_path(@exam), class:"btn btn-outline-primary"%> 
      <%= link_to 'Back to SECTION', @exam.section, class:"btn btn-outline-primary" %>
    </div>
  </div>
</div>
<br/>

<div class="card">
  <div class="card-header">Варианты ответов</div>

  <div class="card-body">
    <table class="table">

      <thead>
        <tr>
          <th></th>
          <th>Вариант ответа</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @exam.answers.each do |answer| %>
          <tr>
            <td><%= answer.correct ? "Правильный" : "-" %></td>
            <td><%= answer.value %></td>
            <td><%= link_to 'Изменить', edit_answer_path(answer) %></td>
            <td><%= link_to 'Удалить', [answer.exam,answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Новый вариант ответа', new_exam_answer_path(@exam), class:"btn btn-outline-secondary" %>
  </div>
</div>
<div class="card">
  <div class="card-header">Рисунки к вопросу</div>

  <div class="card-body">
    <table class="table">

      <thead>
        <tr>
          <th>Название</th>
          <th>Рисунок</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @exam.pics.each do |pic| %>
          <tr>
            <td><%= pic.title %></td>
            <td><%= image_tag pic.img.url(:thumb) %></td>
            <td><%= link_to 'Изменить', edit_pic_path(pic) %></td>
            <td><%= link_to 'Удалить', [pic.exam,pic], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Новый рисунок', new_exam_pic_path(@exam), class:"btn btn-outline-secondary" %>
  </div>
</div>